run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 15
  
  govet:
    check-shadowing: true
  
  golint:
    min-confidence: 0.8
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/felixgeelhaar/gopherFrame

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam

  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - deadcode    # Replaced by unused
    - golint      # Replaced by revive
    - interfacer  # Deprecated
    - maligned    # Replaced by govet fieldalignment
    - structcheck # Replaced by unused
    - varcheck    # Replaced by unused
    - dupl
    - gochecknoglobals
    - gocognit
    - godox
    - gosec
    - lll
    - prealloc

issues:
  exclude-rules:
    # Disable certain linters for test files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - maligned
    
    # Disable line length check for comments with URLs
    - linters:
        - lll
      source: "^//.*http"
    
    # Exclude known false positives
    - text: "G104: Errors unhandled"
      linters:
        - gosec
      path: _test\.go

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0