version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 100
  max-same-issues: 20
