run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 15
  
  govet:
    enable:
      - shadow
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/felixgeelhaar/GopherFrame

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - deferInLoop

  misspell:
    locale: US

  errcheck:
    check-type-assertions: true
    check-blank: false
    ignore: fmt:.*,io/ioutil:^Read.*

  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - github.com/felixgeelhaar/GopherFrame
          - github.com/apache/arrow-go/v18
          - github.com/leanovate/gopter

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - dupl
    - gochecknoglobals
    - gocognit
    - godox
    - gosec
    - lll
    - prealloc

issues:
  exclude-rules:
    # Disable certain linters for test files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - maligned
    
    # Disable line length check for comments with URLs
    - linters:
        - lll
      source: "^//.*http"
    
    # Exclude known false positives
    - text: "G104: Errors unhandled"
      linters:
        - gosec
      path: _test\.go

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0