package gopherframe

import (
	"bytes"
	"encoding/gob"
	"fmt"
	"text/template"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/memory"
	"github.com/felixgeelhaar/GopherFrame/pkg/core"
	"github.com/felixgeelhaar/GopherFrame/pkg/expr"
)

//go:generate echo "GopherFrame UDF code generation ready"

// GenerateUDFCode generates optimized Go source code for a typed UDF.
// This enables go:generate workflows where UDFs are compiled into native functions.
//
// Usage in go:generate workflow:
//
//	//go:generate go run gen_udf.go
//
// The generated code avoids interface{} boxing and runtime type assertions.
func GenerateUDFCode(name string, inputCols []string, inputTypes, outputType arrow.DataType) (string, error) {
	tmpl, err := template.New("udf").Parse(udfTemplate)
	if err != nil {
		return "", fmt.Errorf("template parse error: %w", err)
	}

	data := struct {
		Name       string
		InputCols  []string
		OutputType string
		GoType     string
		BuilderFn  string
	}{
		Name:       name,
		InputCols:  inputCols,
		OutputType: arrowTypeString(outputType),
		GoType:     arrowToGoType(outputType),
		BuilderFn:  arrowToBuilderFn(outputType),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("template execute error: %w", err)
	}
	return buf.String(), nil
}

const udfTemplate = `// Code generated by GopherFrame UDF generator. DO NOT EDIT.
package main

import (
	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/memory"
)

// {{.Name}}UDF is a generated, type-safe UDF implementation.
// Input columns: {{range .InputCols}}{{.}}, {{end}}
// Output type: {{.OutputType}}
func {{.Name}}UDF(record arrow.Record) (arrow.Array, error) {
	pool := memory.NewGoAllocator()
	numRows := int(record.NumRows())
	builder := {{.BuilderFn}}(pool)
	defer builder.Release()

	for i := 0; i < numRows; i++ {
		// TODO: Add generated column access and computation here
		_ = i
	}

	return builder.NewArray(), nil
}
`

func arrowTypeString(dt arrow.DataType) string {
	switch dt.ID() {
	case arrow.FLOAT64:
		return "float64"
	case arrow.INT64:
		return "int64"
	case arrow.STRING:
		return "string"
	case arrow.BOOL:
		return "bool"
	default:
		return "interface{}"
	}
}

func arrowToGoType(dt arrow.DataType) string {
	return arrowTypeString(dt)
}

func arrowToBuilderFn(dt arrow.DataType) string {
	switch dt.ID() {
	case arrow.FLOAT64:
		return "array.NewFloat64Builder"
	case arrow.INT64:
		return "array.NewInt64Builder"
	case arrow.STRING:
		return "array.NewStringBuilder"
	case arrow.BOOL:
		return "array.NewBooleanBuilder"
	default:
		return "array.NewStringBuilder"
	}
}

// --- UDF Serialization ---

// SerializableUDF represents a UDF that can be serialized for distributed execution.
type SerializableUDF struct {
	Name       string
	InputCols  []string
	OutputType string
	Code       string // Go source code of the UDF for remote compilation
}

func init() {
	gob.Register(&SerializableUDF{})
}

// SerializeUDF serializes a UDF specification to bytes for network transfer.
func SerializeUDF(name string, inputCols []string, outputType arrow.DataType, code string) ([]byte, error) {
	udf := &SerializableUDF{
		Name:       name,
		InputCols:  inputCols,
		OutputType: arrowTypeString(outputType),
		Code:       code,
	}

	var buf bytes.Buffer
	enc := gob.NewEncoder(&buf)
	if err := enc.Encode(udf); err != nil {
		return nil, fmt.Errorf("failed to serialize UDF: %w", err)
	}
	return buf.Bytes(), nil
}

// DeserializeUDF deserializes a UDF specification from bytes.
func DeserializeUDF(data []byte) (*SerializableUDF, error) {
	var udf SerializableUDF
	dec := gob.NewDecoder(bytes.NewReader(data))
	if err := dec.Decode(&udf); err != nil {
		return nil, fmt.Errorf("failed to deserialize UDF: %w", err)
	}
	return &udf, nil
}

// --- Multi-value Pivot ---

// PivotMulti transforms long-format data to wide-format with multiple value columns.
// Each value column becomes a set of pivoted columns: <pivotValue>_<valueCol>.
func (df *DataFrame) PivotMulti(indexCols []string, pivotCol string, valueCols []string) *DataFrame {
	if df.err != nil {
		return &DataFrame{err: df.err}
	}
	for _, col := range indexCols {
		if !df.HasColumn(col) {
			return &DataFrame{err: fmt.Errorf("index column not found: %s", col)}
		}
	}
	if !df.HasColumn(pivotCol) {
		return &DataFrame{err: fmt.Errorf("pivot column not found: %s", pivotCol)}
	}
	for _, col := range valueCols {
		if !df.HasColumn(col) {
			return &DataFrame{err: fmt.Errorf("value column not found: %s", col)}
		}
	}

	pool := memory.NewGoAllocator()
	record := df.coreDF.Record()
	schema := record.Schema()
	numRows := int(record.NumRows())

	pivotIdx := findColIdx(schema, pivotCol)
	pivotArr := record.Column(pivotIdx)

	// Get unique pivot values
	pivotValues := make(map[string]bool)
	for i := 0; i < numRows; i++ {
		if !pivotArr.IsNull(i) {
			pivotValues[getStringValue(pivotArr, i)] = true
		}
	}
	pivotKeys := sortedKeys(pivotValues)

	// Build lookup: compositeKey + pivotValue -> map[valueCol]value
	type cellKey struct {
		indexKey string
		pivotVal string
	}
	lookup := make(map[cellKey]map[string]interface{})
	indexKeySet := make(map[string]bool)
	var indexKeyOrder []string

	indexIndices := make([]int, len(indexCols))
	for i, col := range indexCols {
		indexIndices[i] = findColIdx(schema, col)
	}

	for i := 0; i < numRows; i++ {
		var parts []string
		for _, idx := range indexIndices {
			parts = append(parts, getStringValue(record.Column(idx), i))
		}
		ik := fmt.Sprintf("%v", parts)
		if !indexKeySet[ik] {
			indexKeySet[ik] = true
			indexKeyOrder = append(indexKeyOrder, ik)
		}

		pv := getStringValue(pivotArr, i)
		ck := cellKey{indexKey: ik, pivotVal: pv}
		if lookup[ck] == nil {
			lookup[ck] = make(map[string]interface{})
		}
		for _, vc := range valueCols {
			vcIdx := findColIdx(schema, vc)
			lookup[ck][vc] = getTypedValue(record.Column(vcIdx), i)
		}
	}

	// Build index first-row mapping
	indexFirstRow := make(map[string]int)
	for i := 0; i < numRows; i++ {
		var parts []string
		for _, idx := range indexIndices {
			parts = append(parts, getStringValue(record.Column(idx), i))
		}
		ik := fmt.Sprintf("%v", parts)
		if _, exists := indexFirstRow[ik]; !exists {
			indexFirstRow[ik] = i
		}
	}

	resultRows := len(indexKeyOrder)
	var resultFields []arrow.Field
	var resultColumns []arrow.Array

	// Add index columns
	for _, ic := range indexCols {
		idx := findColIdx(schema, ic)
		resultFields = append(resultFields, schema.Field(idx))
		srcArr := record.Column(idx)
		b := array.NewStringBuilder(pool)
		for _, ik := range indexKeyOrder {
			ri := indexFirstRow[ik]
			b.Append(getStringValue(srcArr, ri))
		}
		resultColumns = append(resultColumns, b.NewArray())
		b.Release()
	}

	// Add pivoted value columns: <pivotVal>_<valueCol>
	for _, pv := range pivotKeys {
		for _, vc := range valueCols {
			colName := pv + "_" + vc
			resultFields = append(resultFields, arrow.Field{Name: colName, Type: arrow.PrimitiveTypes.Float64})
			b := array.NewFloat64Builder(pool)
			for _, ik := range indexKeyOrder {
				ck := cellKey{indexKey: ik, pivotVal: pv}
				vals := lookup[ck]
				if vals == nil || vals[vc] == nil {
					b.AppendNull()
				} else {
					switch v := vals[vc].(type) {
					case float64:
						b.Append(v)
					case int64:
						b.Append(float64(v))
					default:
						b.AppendNull()
					}
				}
			}
			resultColumns = append(resultColumns, b.NewArray())
			b.Release()
		}
	}

	resultSchema := arrow.NewSchema(resultFields, nil)
	resultRecord := array.NewRecord(resultSchema, resultColumns, int64(resultRows))
	return NewDataFrame(resultRecord)
}

// Ensure UDF expressions are compilable (interface satisfaction check)
var _ expr.Expr = (*scalarUDFExpr)(nil)
var _ expr.Expr = (*vectorUDFExpr)(nil)
var _ expr.Expr = (*constantFoldedExpr)(nil)

// Ensure core DataFrame is accessible
var _ = (*core.DataFrame)(nil)
